# New York Taxi Rides

The purpose of this project is to analyze a dataset consisting of approximately 90,000 taxi cab rides that took place in New York in June of 2016. This is my first project learning and utilizing NumPy.

In [1]:
# import csv, numpy; create ndarray of dataset

import csv
import numpy as np
np.set_printoptions(suppress=True)

opened_file = open(r'C:\Users\asang\Downloads\nyc_taxis.csv', 'r')
taxi_list = list(csv.reader(opened_file))
taxi_header, taxi = taxi_list[0], taxi_list[1:]

# Convert all values to floats
converted_taxi = []
for row in taxi:
    converted_row = []
    for each_item in row:
        converted_row.append(float(each_item))
    converted_taxi.append(converted_row)
    
taxi = np.array(converted_taxi)
taxi_shape = taxi.shape
print('There are {} rows and {} columns: '.format(taxi_shape[0], taxi_shape[1]), '\n')

for label in enumerate(taxi_header):
    print(label)

There are 89560 rows and 15 columns:  

(0, 'pickup_year')
(1, 'pickup_month')
(2, 'pickup_day')
(3, 'pickup_dayofweek')
(4, 'pickup_time')
(5, 'pickup_location_code')
(6, 'dropoff_location_code')
(7, 'trip_distance')
(8, 'trip_length')
(9, 'fare_amount')
(10, 'fees_amount')
(11, 'tolls_amount')
(12, 'tip_amount')
(13, 'total_amount')
(14, 'payment_type')


***
Next I will calculate the sum of fares and fees.

In [2]:
fares = taxi[:, 9]
fees = taxi[:, 10]
fares_and_fees = fares + fees
print(fares_and_fees)

[52.8 46.3 37.8 ... 52.8 35.8 49.3]


***
Calculating the average travel speed of each trip in miles per hour would be useful.

In [3]:
trip_distance_miles = taxi[:, 7]
trip_length_hours = taxi[:, 8] / 3600

trip_mph = trip_distance_miles / trip_length_hours
mph_max = trip_mph.max()
mph_mean = trip_mph.mean()

print("The max mph is {}, and the average mph is {}".format(mph_max, mph_mean))

The max mph is 82800.0, and the average mph is 32.24258580925573


***
Now I will do some statistical analysis on specific columns to verify the total amounts are accurate.

In [21]:
taxi_first_five = taxi[:5]
fare_components = taxi_first_five[:, 9:13]
print(taxi_header[9:13], '\n')
print(fare_components, '\n')

fare_sums = fare_components.sum(axis=1)
print(fare_sums, '\n')
fare_totals = taxi_first_five[:, 13]
print(fare_totals)

['fare_amount', 'fees_amount', 'tolls_amount', 'tip_amount'] 

[[52.    0.8   5.54 11.65]
 [45.    1.3   0.    8.  ]
 [36.5   1.3   0.    0.  ]
 [26.    1.3   0.    5.46]
 [17.5   1.3   0.    0.  ]] 

[69.99 54.3  37.8  32.76 18.8 ] 

[69.99 54.3  37.8  32.76 18.8 ]


Verified that the data in the fare totals column is accurate.
***