# Learning NumPy
Done using numpy.org via the absolute beginner guide.
- Vectors and matrices are created from the `ndarray` class.
- Dimensions are called `axes`.


### Getting started with arrays

In [12]:
import numpy as np

In [26]:
a = np.array([1, 2, 3, 4, 5, 6]) # 1-dimensional array is called a vector
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # # 2-dimensional array is called a matrix
c = np.array([[[1, 1, 1], 
               [2, 2, 2],
               [3, 3, 3]],

              [[1, 1, 1], 
               [2, 2, 2],
               [3, 3, 3]]]) # < 2-dimensional array is commonly called a tensor

In [27]:
print(a.shape)
print(b.shape)
print(c.shape)

(6,)
(3, 3)
(2, 3, 3)


In [22]:
print(b[1]) # accesses 2nd array in the matrix

[4 5 6]


### How to create basic arrays

In [28]:
a = np.array([1, 2, 3]) # python lists can be passed in

In [39]:
print(np.zeros(5)) # creates an array of zeros

[0. 0. 0. 0. 0.]


In [40]:
# pass a list of dimensions to specify size:
print(np.zeros([2, 5, 3]))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [31]:
np.ones(3) # creates an array of ones

array([1., 1., 1.])

In [32]:
np.empty(4) # creates an array from random digits in memory

array([1.72723371e-077, 1.29073941e-231, 1.73059733e-077, 2.82469002e-309])

In [41]:
# create an array with a specified range:
np.arange(4) # 1-dimensional up to 4 exclusive

array([0, 1, 2, 3])

In [42]:
np.arange(10) # 1-dimensional array up to 10 exclusive

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# just like with python range function, you can specify start, stop, and step:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
# this creates an array, and you get to specify the start and stop, and the num keyword specifies how many elements should be used to fill the specified range:
np.linspace(0, 20, num=10) # this says to have 10 elements starting from 0 to 20

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [49]:
# data type can be specified when creating arrays:
x = np.arange(3, dtype=np.int64)
x

array([0, 1, 2])

### Adding, removing, and sorting elements

In [50]:
arr = np.array([6, 4, 7, 8, 2, 3, 0])
np.sort(arr) # this functions sorts an array numerically

array([0, 2, 3, 4, 6, 7, 8])

In [54]:
# in order to concatenate arrays, use the np.concatenate function and passing the arrays as a tuple:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
x = np.array([[1, 2], [4, 5]])
y = np.array([[5, 6]])
np.concatenate((x, y))

array([[1, 2],
       [4, 5],
       [5, 6]])

In order to remove elements from an array, it’s simple to use indexing to select the elements that you want to keep.

### How to know the size and shape of an array